# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
author: Normativity Lab
name: NeurIPS 2024 Tutorial
title: Cross-disciplinary insights into Alignment in Humans and Machines
email:
description: >
  NeurIPS 2024 Tutorial on Advanced Topics in Multimodal Machine Learning
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a
          href="https://github.com/alshedivat/al-folio">al-folio</a> theme and sourced from <a
          href="https://cmu-multicomp-lab.github.io/adv-mmml-course/spring2023/">CMU AMMML</a>.

url:  # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/



# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
# github_username: find_one
# google_analytics: x
# youtube_channel: 
rss:  # notes rss

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Tutorial Notes
blog_description: More details on the tutorial

# Pagination
paginate: 10
permalink: /notes/:title/
paginate_path: /notes/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
# disqus_shortname: # put your disqus shortname


# Optional features
show_social_icons:  true
enable_anchorjs:    true
enable_latexjs:     true
enable_katex:       true

# -----------------------------------------------------------------------------
# Comments 
# -----------------------------------------------------------------------------
comments:
  giscus:
    enabled: true
    repo: "TheNormativityLab/neurips24discussion"
    repo_id: "R_kgDONX5YQw"
    category: "General"
    category_id: "DIC_kwDONX5YQ84Ck0dY"



# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  announcements:
    defaults:
      layout: post
    output: true
    permalink: /announcements/:path/

announcements_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.10.1"
anchorjs_version: "3.2.2"
latexjs_version: "0.11.1"

theme: jekyll-theme-slate


